### ISSUE TITLE
Update socket.io versions?

### ISSUE THREAD

**Issue by cristiano-belloni** [shSina/socket.io-client#1]
It seems this repo is not maintained anymore?

**Comment by sshbio** [comment]
thanks for reminding , the server watching changes has been disabled.

**Comment by cristiano-belloni** [comment]
Hi, would it be a burden to update also the intermediate ones? There's a library, skylinkjs, depending on 1.3.7, that won't work on bower.

**Comment by sshbio** [comment]
hi , I will add them too

**Comment by cristiano-belloni** [comment]
Thanks!
